name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: katex_and_theme
      run: pip install sphinxcontrib-katex sphinx-rtd-theme
    - id: deployment
      uses: sphinx-notes/pages@v3
